### ISSUE TITLE
Will there be a linux version in the future? 

### ISSUE THREAD

**Issue by linusrg1** [kawaiizenbo/RepoFullDownloader#2]
This tool looks cool but unfortunately I cant use it.

**Comment by kawaiizenbo** [comment]
quite possibly, this would be a relatively easy port.

**Comment by linusrg1** [comment]
huh ok cool! thx

**Comment by kawaiizenbo** [comment]
totally forgot sorry but ported it on october https://github.com/kawaiizenbo/RepoFullDownloader-Core
